### ISSUE TITLE
Optional new pid type?

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-rdm-migrator#31]
Should we have an option to allow minting new pid types and legacy pids?

**Comment by ppanero** [comment]
Could you exemplify a use case? At the moment, we have a minimalistic way of minting new pids (see `load.ids` module and their usage) and more complex logic is not needed up-to-now in the Zenodo migration since we are keeping the old PIDs.

Closing issue... feel free to re-open if it is required for some use case.
